### ISSUE TITLE
Got error: socket hang up

### ISSUE THREAD

**Issue by jaychsu** [yoshuawuyts/markdown-to-medium#18]
I've checked my network in CLI, but still got the error below. Any idea to resolve it?

Action what I do:

```
markdown-to-medium ./test.md --token=$MY_TOKEN_JUST_CREATED
```

Error message:

```
~/.config/yarn/global/node_modules/markdown-to-medium/index.js:88
      throw new Error(err)
      ^

Error: Error: socket hang up
    at client.getUser (/Users/jaychsu/.config/yarn/global/node_modules/markdown-to-medium/index.js:88:13)
    at ClientRequest.<anonymous> (/Users/jaychsu/.config/yarn/global/node_modules/medium-sdk/lib/mediumClient.js:380:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketCloseListener (_http_client.js:285:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

**Comment by RichardLitt** [comment]
I was unable to replicate this both locally and with the published package. Are you sure your token is correct, and from Medium? Can you try on a different network?

**Comment by jaychsu** [comment]
For token:
I copied it from the section `Integration tokens` in `https://medium.com/me/settings`, and the shape of token like this: `2f2888c20490d9c48093e0cc5797718ade6ad194703711bce488f************`.

For network:
Let me do more check and I'll give you a feedback. ;)

**Comment by jaychsu** [comment]
Hi, This error was caused by the failure of the proxy server used by my CLI.
This lib works properly. 👍

**Comment by RichardLitt** [comment]
Thought so! Glad to hear you got it fixed.

**Comment by loganpowell** [comment]
@jaychsu I'm having this same issue. It has worked for me in the past, but now it's throwing this error... How did you fix/work around it?

```

Error: Error: socket hang up
    at client.createPost (C:\Users\surface\AppData\Roaming\npm\node_modules\markdown-to-medium\index.js:126:17)
    at ClientRequest.<anonymous> (C:\Users\surface\AppData\Roaming\npm\node_modules\markdown-to-medium\node_modules\medium-sdk\lib\mediumClient.js:380:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketCloseListener (_http_client.js:363:9)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:554:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```
