### ISSUE TITLE
Error: Application not found

### ISSUE THREAD

**Issue by ashryanbeats** [yoshuawuyts/markdown-to-medium#21]
Is anyone else getting an "Application not found" error when running this module? It's been fine until the last week or so.

It looks like one of the dependencies is no longer maintained by Medium:
https://github.com/Medium/medium-sdk-nodejs

Stack trace:

```
~/n/lib/node_modules/markdown-to-medium/index.js:88
      throw new Error(err)
      ^

Error: Error: Application not found
    at client.getUser (~/n/lib/node_modules/markdown-to-medium/index.js:88:13)
    at IncomingMessage.<anonymous> (~/n/lib/node_modules/markdown-to-medium/node_modules/medium-sdk/lib/mediumClient.js:372:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Tried this with both Node.js v8.9 and v10.13.

**Comment by pavloo** [comment]
I have this problem too. Any ideas? Did medium just shut down their Node SDK?

**Comment by RichardLitt** [comment]
Bizarre. I'll check this out the next time I publish to Medium - should be in the next week or so.
