### ISSUE TITLE
'token should be a string' error

### ISSUE THREAD

**Issue by neuroplastic** [yoshuawuyts/markdown-to-medium#7]
Getting this error when trying to run markdown-to-medium for the first time, passing the token:

```
markdown-to-medium decent.txt --token

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: markdown-to-medium: token should be a string
    at main (/usr/local/lib/node_modules/markdown-to-medium/index.js:18:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdown-to-medium/bin/cli.js:47:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```
Have tried wrapping the token in quotes. Any clues?

**Comment by RichardLitt** [comment]
Can you give us an example with the syntax you're using? It's unclear above whether you have included the token or not - looks like you removed it. Can you post with an obfuscated or false token, so we can just check the syntax and duplicate on our end?

**Comment by RichardLitt** [comment]
ping @neuroplastic

**Comment by RichardLitt** [comment]
Closing as unresponsive. Reopen as needed.
